[package]
name = "sentry-uploader"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1"
httpdate = "1"
reqwest = { version = "0.11", features = ["json"], default-features = false }
sentry-core = "0.23"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
